version: 0.0
os: linux
files:
   - source: /
     destination: /var/www/html/wp
permissions:
   - object: /var/www/html/wp
     pattern: "**"
     owner: www-data
     group: www-data
     mode: 644
     type:
       - file
   - object: /var/www/html/telsimadmin
     pattern: "**"
     owner: www-data
     group: www-data
     mode: 755
     type:
       - folder
       
hooks:
   AfterInstall:
    - location: hooks/after-install.sh
      runas: root
